// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvm8A7JNleTSiMkZdVnVS5DRnaXjIESTs',
    appId: '1:1000568613849:web:01dc2ebf8c23e0b8f847c8',
    messagingSenderId: '1000568613849',
    projectId: 'zeepalm-flutter',
    authDomain: 'zeepalm-flutter.firebaseapp.com',
    databaseURL: "https://zeepalm-flutter-default-rtdb.firebaseio.com",
    storageBucket: 'zeepalm-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkC3PyoHtIqXbktexcfYpOD0T0sCxVI5s',
    appId: '1:1000568613849:android:295284d95b385bd4f847c8',
    messagingSenderId: '1000568613849',
    projectId: 'zeepalm-flutter',
    storageBucket: 'zeepalm-flutter.appspot.com',
    databaseURL: "https://zeepalm-flutter-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiKoP4zM1d3tbI7jUryMma_YXwjj9s44g',
    appId: '1:1000568613849:ios:39ba8dab091c11b8f847c8',
    messagingSenderId: '1000568613849',
    projectId: 'zeepalm-flutter',
    storageBucket: 'zeepalm-flutter.appspot.com',
    iosBundleId: 'com.example.zeepalmtodo',
    databaseURL: "https://zeepalm-flutter-default-rtdb.firebaseio.com",
  );
}
